import { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import MainIndex from "@/MainIndex";

// Import Outfit font with specified weights
const outfit = Outfit({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <MainIndex>
          {children}
        </MainIndex>
      </body>
    </html>
  );
}
